[package]
name = "rust"
version = "0.1.0"
authors = ["Noah Pendleton <2538614+noahp@users.noreply.github.com>"]
edition = "2018"

[lib]
crate_type = ["dylib"]

[dependencies]
ctor = "0.1.13"

[build-dependencies]
bindgen = "0.53.2"
